name: androidflutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  get_cli: ^1.5.0
  cupertino_icons: ^1.0.0
  get: 4.1.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/ikon_materi.png
    - assets/images/pp_laki.png
    - assets/images/Card-Modul.png
    - assets/images/Card-Media.png
    - assets/images/list-modul.png
    - assets/images/bg.jpg
    - assets/images/notifikasi.png
  uses-material-design: true

